# Generated by Django 5.2.5 on 2025-09-14 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the service category (e.g., 'Screen Printing').", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly version of the name (auto-generated).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of what this service category entails.', null=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A recognizable name for the machine, e.g., 'HP Indigo' or 'Main Laminator'.", max_length=100)),
                ('machine_type', models.CharField(choices=[('DIGITAL', 'Digital Press'), ('OFFSET', 'Offset Press'), ('SCREEN', 'Screen Printer'), ('LARGE_FORMAT', 'Large Format Printer'), ('UV_DTF', 'UV DTF Printer'), ('UV_FLA', 'UV Flatbed Printer'), ('FLATBED', 'Flatbed Printer'), ('LASER', 'Laser Printer'), ('ROUTER', 'Router Printer'), ('LAMINATOR', 'Lamination Machine'), ('UV', 'UV Lamination Machine'), ('BINDING', 'Binding Machine'), ('CUTTER', 'Cutter'), ('FINISHING', 'Finishing Machine'), ('OTHER', 'Other')], default='DIGITAL', max_length=50)),
                ('supports_client_custom_size', models.BooleanField(default=False, verbose_name='Supports custom sizes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.printcompany')),
                ('supported_sizes', models.ManyToManyField(blank=True, related_name='supported_machines', to='papers.finalpapersize', verbose_name='Supported standard sizes')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
