# Generated by Django 5.2.4 on 2025-10-21 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A recognizable name for the machine, e.g., 'HP Indigo' or 'Main Laminator'.", max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('machine_type', models.CharField(choices=[('DIGITAL', 'Digital Press'), ('OFFSET', 'Offset Press'), ('SCREEN', 'Screen Printer'), ('LARGE_FORMAT', 'Large Format Printer'), ('UV_DTF', 'UV DTF Printer'), ('UV_FLATBED', 'UV Flatbed Printer'), ('FLATBED', 'Flatbed Printer'), ('LASER', 'Laser Printer'), ('ROUTER', 'Router Printer'), ('LAMINATOR', 'Lamination Machine'), ('UV', 'UV Lamination Machine'), ('BINDING', 'Binding Machine'), ('CUTTER', 'Cutter'), ('FINISHING', 'Finishing Machine'), ('OTHER', 'Other')], default='DIGITAL', max_length=50)),
                ('supports_client_custom_size', models.BooleanField(default=False, verbose_name='Supports custom sizes')),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_finishing_services', to='core.printcompany')),
                ('default_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sheet_for_machines', to='papers.productionpapersize')),
                ('supported_sizes', models.ManyToManyField(blank=True, related_name='supported_machines', to='papers.productionpapersize', verbose_name='Supported standard sizes')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'constraints': [models.UniqueConstraint(fields=('company', 'machine_type', 'name'), name='unique_machine_per_company_type_name')],
            },
        ),
    ]
