# Generated by Django 5.2.4 on 2025-10-20 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A recognizable name for the machine, e.g., 'HP Indigo' or 'Main Laminator'.", max_length=100)),
                ('machine_type', models.CharField(choices=[('DIGITAL', 'Digital Press'), ('OFFSET', 'Offset Press'), ('SCREEN', 'Screen Printer'), ('LARGE_FORMAT', 'Large Format Printer'), ('UV_DTF', 'UV DTF Printer'), ('UV_FLA', 'UV Flatbed Printer'), ('FLATBED', 'Flatbed Printer'), ('LASER', 'Laser Printer'), ('ROUTER', 'Router Printer'), ('LAMINATOR', 'Lamination Machine'), ('UV', 'UV Lamination Machine'), ('BINDING', 'Binding Machine'), ('CUTTER', 'Cutter'), ('FINISHING', 'Finishing Machine'), ('OTHER', 'Other')], default='DIGITAL', max_length=50)),
                ('supports_client_custom_size', models.BooleanField(default=False, verbose_name='Supports custom sizes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_finishing_services', to='core.printcompany')),
                ('default_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sheet_for_machines', to='papers.productionpapersize')),
                ('supported_sizes', models.ManyToManyField(blank=True, related_name='supported_machines', to='papers.productionpapersize', verbose_name='Supported standard sizes')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FinishingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, unique=True)),
                ('calculation_method', models.CharField(choices=[('PER_JOB', 'Flat rate per job'), ('PER_SET', 'Per set (e.g., per book, per bundle)'), ('PER_COPY', 'Per printed copy'), ('PER_SHEET', 'Per sheet'), ('PER_SHEET_PER_SIDE', 'Per sheet per side')], default='PER_JOB', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_services', to='core.printcompany')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_services', to='papers.productionpapersize')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_services', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Finishing Service',
                'verbose_name_plural': 'Finishing Services',
                'unique_together': {('company', 'machine', 'name', 'size')},
            },
        ),
    ]
