# Generated by Django 5.2.4 on 2025-10-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finishingservice',
            unique_together={('company', 'machine', 'name')},
        ),
        migrations.AddField(
            model_name='finishingservice',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='finishing_services', to='papers.productionpapersize'),
        ),
        migrations.AlterField(
            model_name='finishingservice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_finishing_services', to='core.printcompany'),
        ),
        migrations.RemoveField(
            model_name='finishingservice',
            name='size',
        ),
    ]
