# Generated by Django 5.2.4 on 2025-10-12 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UVDTFMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('finish', models.CharField(blank=True, max_length=100, verbose_name='finish')),
            ],
            options={
                'verbose_name': 'UV DTF material',
                'verbose_name_plural': 'UV DTF materials',
            },
        ),
        migrations.CreateModel(
            name='FinalPaperSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='width (mm)')),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='height (mm)')),
                ('size_type', models.CharField(choices=[('production', 'Production'), ('final', 'Final')], max_length=20, verbose_name='size type')),
            ],
            options={
                'verbose_name': 'Final size',
                'verbose_name_plural': 'Final sizes',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('name', 'width_mm', 'height_mm')},
            },
        ),
        migrations.CreateModel(
            name='LargeFormatMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('material_type', models.CharField(max_length=100, verbose_name='material type')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='thickness (mm)')),
                ('width_mm', models.DecimalField(decimal_places=2, help_text='The total width of the material in mm.', max_digits=10, verbose_name='width (mm)')),
            ],
            options={
                'verbose_name': 'Large format material',
                'verbose_name_plural': 'Large format materials',
                'unique_together': {('name', 'width_mm')},
            },
        ),
        migrations.CreateModel(
            name='ProductionPaperSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='width (mm)')),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='height (mm)')),
                ('size_type', models.CharField(choices=[('production', 'Production'), ('final', 'Final')], max_length=20, verbose_name='size type')),
            ],
            options={
                'verbose_name': 'Printing paper size',
                'verbose_name_plural': 'Printing paper sizes',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('name', 'width_mm', 'height_mm')},
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('gsm', models.PositiveIntegerField(verbose_name='gsm')),
                ('is_coated', models.BooleanField(default=False, verbose_name='is coated')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('is_banner', models.BooleanField(default=False, help_text='True if this is banner material')),
                ('is_special', models.BooleanField(default=False, help_text='True if this is a special material like Tic Tac')),
                ('size', models.ForeignKey(blank=True, help_text='Default sheet size', null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.productionpapersize')),
            ],
            options={
                'verbose_name': 'Digital paper type',
                'verbose_name_plural': 'Digital paper types',
                'unique_together': {('name', 'gsm')},
            },
        ),
    ]
