# Generated by Django 5.2.4 on 2025-10-17 19:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the service category (e.g., 'Screen Printing').", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly version of the name (auto-generated).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of what this service category entails.', null=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude (Y)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude (X)')),
                ('primary_color', models.CharField(blank=True, help_text="Primary theme color for the company's page (e.g., #0A3D62).", max_length=7, null=True, verbose_name='primary color')),
                ('secondary_color', models.CharField(blank=True, help_text='Secondary theme color for accents and links (e.g., #FF9F43).', max_length=7, null=True, verbose_name='secondary color')),
                ('current_busy_level', models.PositiveIntegerField(choices=[(1, 'Least Busy (Faster Turnaround)'), (2, 'Less Busy'), (3, 'Average'), (4, 'Busy'), (5, 'Very Busy (Longer Turnaround)')], default=3, help_text='Set your current production capacity (1=Fastest, 5=Slowest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(help_text='The user account that owns and manages this company.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_print_company', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, help_text='Select all the services this company provides.', related_name='companies', to='core.servicecategory', verbose_name='services offered')),
            ],
            options={
                'verbose_name_plural': 'Print Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items may be displayed more prominently.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='core.printcompany')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-date_completed'],
            },
        ),
    ]
