# Generated by Django 5.2.4 on 2025-10-21 21:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetPlatePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('setup_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_plate_prices_company', to='core.printcompany')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_plate_prices_machine', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenRunPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_cost_per_item_per_color', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_run_prices_company', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'SCREEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='screen_run_prices', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSetupPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('setup_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_setup_prices_company', to='core.printcompany')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_prices_machine', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='UVDTFPrintPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvdtf_print_prices_company', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'UV_DTF'}, on_delete=django.db.models.deletion.CASCADE, related_name='uvdtf_prices', to='machines.machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='papers.uvdtfmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrintPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('single_side_price', models.DecimalField(decimal_places=2, help_text='Price per sheet (single-sided).', max_digits=10)),
                ('double_side_price', models.DecimalField(decimal_places=2, help_text='Price per sheet (double-sided).', max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(help_text='The company this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='digital_print_prices', to='core.printcompany')),
                ('machine', models.ForeignKey(help_text='The digital press this pricing applies to.', limit_choices_to={'machine_type': 'DIGITAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='digital_prices', to='machines.machine')),
                ('paper_type', models.ForeignKey(help_text='The paper stock this pricing applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='digital_prices', to='papers.papertype')),
                ('size', models.ForeignKey(blank=True, help_text='Default production sheet size for this price (e.g., SRA3).', null=True, on_delete=django.db.models.deletion.PROTECT, to='papers.productionpapersize')),
            ],
            options={
                'verbose_name': 'Digital Print Price',
                'verbose_name_plural': 'Digital Print Prices',
                'ordering': ['paper_type__name'],
                'constraints': [models.UniqueConstraint(fields=('machine', 'paper_type'), name='unique_digital_machine_paper')],
            },
        ),
        migrations.CreateModel(
            name='LaminationPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('single_side_price', models.DecimalField(decimal_places=2, help_text='Price per sheet (single-sided lamination).', max_digits=10)),
                ('double_side_price', models.DecimalField(decimal_places=2, help_text='Price per sheet (double-sided lamination).', max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(help_text='The company this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lamination_prices_company', to='core.printcompany')),
                ('lamination_type', models.ForeignKey(help_text='Type of lamination material, e.g., matte, gloss, frost, velvet.', on_delete=django.db.models.deletion.CASCADE, related_name='lamination_prices_lamination_type', to='papers.laminationmaterial')),
                ('machine', models.ForeignKey(help_text='The laminator this pricing applies to.', limit_choices_to={'machine_type': 'LAMINATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='lamination_prices_machine', to='machines.machine')),
                ('size', models.ForeignKey(blank=True, help_text='Default production sheet size for this price (e.g., SRA3).', null=True, on_delete=django.db.models.deletion.PROTECT, to='papers.productionpapersize')),
            ],
            options={
                'verbose_name': 'Lamination Price',
                'verbose_name_plural': 'Lamination Prices',
                'ordering': ['lamination_type__name'],
                'constraints': [models.UniqueConstraint(fields=('machine', 'lamination_type'), name='unique_laminator_machine_laminationtype')],
            },
        ),
        migrations.CreateModel(
            name='LargeFormatPrintPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_width_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_format_prices', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'LARGE_FORMAT'}, on_delete=django.db.models.deletion.CASCADE, related_name='large_format_prices', to='machines.machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_format_material_prices', to='papers.largeformatmaterial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('machine', 'material', 'roll_width_m'), name='unique_largeformat_machine_material_width')],
            },
        ),
        migrations.CreateModel(
            name='OffsetRunPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_sheet_per_color', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_run_prices_company', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'OFFSET'}, on_delete=django.db.models.deletion.CASCADE, related_name='offset_run_prices_machine', to='machines.machine')),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_run_prices_paper_type', to='papers.papertype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('machine', 'paper_type'), name='unique_offset_machine_paper')],
            },
        ),
        migrations.CreateModel(
            name='TieredFinishingPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text="Quantity from which this tier's pricing begins.", verbose_name='Minimum Quantity')),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text="Quantity up to which this tier's pricing applies.", verbose_name='Maximum Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit within this tier.', max_digits=10, verbose_name='Unit Price')),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional setup or handling fee for this tier.', max_digits=10, verbose_name='Setup Fee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_finishing_prices', to='core.printcompany', verbose_name='Print Company')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_finishing_prices_machine', to='machines.machine', verbose_name='Machine')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_finishing_prices_service', to='machines.machine', verbose_name='Finishing Service')),
            ],
            options={
                'verbose_name': 'Tiered Finishing Price',
                'verbose_name_plural': 'Tiered Finishing Prices',
                'ordering': ['company', 'machine', 'service', 'min_quantity'],
                'unique_together': {('company', 'machine', 'service', 'min_quantity', 'max_quantity')},
            },
        ),
    ]
