# Generated by Django 5.2.4 on 2025-10-17 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetPlatePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'A3+ Plate'", max_length=100)),
                ('setup_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_plate_prices', to='core.printcompany')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenRunPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_cost_per_item_per_color', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_run_prices', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'SCREEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='screen_run_prices', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSetupPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Standard A3 Screen'", max_length=100)),
                ('setup_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_setup_prices', to='core.printcompany')),
            ],
        ),
        migrations.CreateModel(
            name='TieredFinishingPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_prices', to='machines.finishingservice')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='UVDTFPrintPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvdtf_print_prices', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'UV_DTF'}, on_delete=django.db.models.deletion.CASCADE, related_name='uvdtf_prices', to='machines.machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='papers.uvdtfmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrintPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('single_side_price', models.DecimalField(decimal_places=2, help_text='Price per sheet (single-sided).', max_digits=10)),
                ('double_side_price', models.DecimalField(decimal_places=2, help_text='Price per sheet (double-sided).', max_digits=10)),
                ('currency', models.CharField(default='KES', help_text='Currency for the pricing (e.g., KES, USD).', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, help_text='The minimum total charge for any job using this price.', max_digits=10)),
                ('company', models.ForeignKey(help_text='The company this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='digital_print_prices', to='core.printcompany')),
                ('machine', models.ForeignKey(help_text='The digital press this pricing applies to.', limit_choices_to={'machine_type': 'DIGITAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='digital_prices', to='machines.machine')),
                ('paper_type', models.ForeignKey(help_text='The paper stock this pricing applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='digital_prices', to='papers.papertype')),
                ('size', models.ForeignKey(blank=True, help_text='Default production sheet size for this price (e.g., SRA3).', null=True, on_delete=django.db.models.deletion.PROTECT, to='papers.productionpapersize')),
            ],
            options={
                'verbose_name': 'Digital Print Price',
                'verbose_name_plural': 'Digital Print Prices',
                'ordering': ['paper_type__name'],
                'unique_together': {('machine', 'paper_type')},
            },
        ),
        migrations.CreateModel(
            name='LargeFormatPrintPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_width_m', models.DecimalField(decimal_places=2, help_text='Width of the roll in meters.', max_digits=5)),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_format_prices', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'LARGE_FORMAT'}, on_delete=django.db.models.deletion.CASCADE, related_name='large_format_prices', to='machines.machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='papers.largeformatmaterial')),
            ],
            options={
                'unique_together': {('machine', 'material', 'roll_width_m')},
            },
        ),
        migrations.CreateModel(
            name='OffsetRunPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_sheet_per_color', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_run_prices', to='core.printcompany')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type': 'OFFSET'}, on_delete=django.db.models.deletion.CASCADE, related_name='offset_run_prices', to='machines.machine')),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_run_prices', to='papers.papertype')),
            ],
            options={
                'unique_together': {('machine', 'paper_type')},
            },
        ),
    ]
