# Generated by Django 5.2.4 on 2025-10-17 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaffprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.printcompany'),
        ),
        migrations.AddField(
            model_name='companystaffprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type__in': ['company_owner', 'company_admin', 'staff']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
        migrations.AddConstraint(
            model_name='companystaffprofile',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_staff_per_company'),
        ),
    ]
