# Generated by Django 5.2.4 on 2025-10-20 05:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
        ('papers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableFinishing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applies_to', models.CharField(choices=[('cover', 'Cover only'), ('inner', 'Inner pages only'), ('whole', 'Entire product')], default='whole', max_length=8)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Optional override quantity for the finishing calculation.', null=True)),
                ('unit_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_links', to='machines.finishingservice')),
            ],
        ),
        migrations.CreateModel(
            name='JobDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to', models.CharField(choices=[('cover', 'Cover only'), ('inner', 'Inner pages only'), ('whole', 'Entire product')], default='whole', max_length=8)),
                ('name', models.CharField(help_text="e.g., 'Book – Title XYZ'", max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sides', models.CharField(choices=[('S1', 'Single-sided'), ('S2', 'Double-sided')], default='S2', max_length=2)),
                ('is_booklet', models.BooleanField(default=False)),
                ('cover_sides', models.CharField(choices=[('S1', 'Single-sided'), ('S2', 'Double-sided')], default='S1', max_length=2)),
                ('page_count', models.PositiveIntegerField(default=1, help_text='Total pages including cover if booklet')),
                ('sets', models.PositiveIntegerField(default=1)),
                ('binding', models.CharField(choices=[('NONE', 'None'), ('SADDLE', 'Saddle Stitch'), ('PERFECT', 'Perfect Bind')], default='NONE', max_length=12)),
                ('sheets_needed', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bleed_mm', models.PositiveIntegerField(default=3)),
                ('gutter_mm', models.PositiveIntegerField(default=2)),
                ('gripper_mm', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('cover_machine', models.ForeignKey(blank=True, limit_choices_to={'machine_type__in': ['DIGITAL', 'UV_FLA', 'LARGE_FORMAT']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_job_deliverables', to='machines.machine')),
                ('cover_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_job_deliverables', to='papers.papertype')),
                ('finishings', models.ManyToManyField(blank=True, related_name='deliverables', through='orders.DeliverableFinishing', to='machines.finishingservice')),
                ('machine', models.ForeignKey(limit_choices_to={'machine_type__in': ['DIGITAL', 'UV_FLA', 'LARGE_FORMAT']}, on_delete=django.db.models.deletion.PROTECT, related_name='job_deliverables', to='machines.machine')),
                ('material', models.ForeignKey(help_text='The paper stock this pricing applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='papers.papertype')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='papers.finalpapersize')),
                ('source_template', models.ForeignKey(blank=True, help_text='The product template this deliverable is based on, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='products.producttemplate')),
            ],
            options={
                'verbose_name': 'job deliverable',
                'verbose_name_plural': 'job deliverables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverablefinishing',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_finishings', to='orders.jobdeliverable'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_ref', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Job Reference')),
                ('name', models.CharField(help_text="Short description e.g. 'Business cards for ACME'", max_length=120)),
                ('status', models.CharField(choices=[('pending_quote', 'Pending Quote'), ('quote_sent', 'Quote Sent'), ('quote_accepted', 'Quote Accepted'), ('paid', 'Paid'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_quote', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instant_quote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(help_text='The client/user who placed the order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(help_text='The print company assigned or requested for this order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.printcompany')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobdeliverable',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverablefinishing',
            unique_together={('deliverable', 'service', 'applies_to')},
        ),
    ]
