# Generated by Django 5.2.5 on 2025-09-14 21:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
        ('papers', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableFinishing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applies_to', models.CharField(choices=[('cover', 'Cover only'), ('inner', 'Inner pages only'), ('book', 'Whole book / assembly')], default='book', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.finishingservice')),
            ],
            options={
                'verbose_name': 'deliverable finishing',
                'verbose_name_plural': 'deliverable finishings',
            },
        ),
        migrations.CreateModel(
            name='JobDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Book – Title XYZ'", max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_booklet', models.BooleanField(default=False)),
                ('page_count', models.PositiveIntegerField(default=1, help_text='Total pages including cover if booklet')),
                ('cover_sidedness', models.CharField(choices=[('S1', 'Single-sided'), ('S2', 'Double-sided')], default='S1', max_length=2)),
                ('inner_sidedness', models.CharField(choices=[('S1', 'Single-sided'), ('S2', 'Double-sided')], default='S2', max_length=2)),
                ('binding', models.CharField(choices=[('NONE', 'None'), ('SADDLE', 'Saddle Stitch'), ('PERFECT', 'Perfect Bind')], default='NONE', max_length=12)),
                ('bleed_mm', models.PositiveIntegerField(default=3)),
                ('gutter_mm', models.PositiveIntegerField(default=5)),
                ('gripper_mm', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_machine', models.ForeignKey(blank=True, limit_choices_to={'machine_type__in': ['DIGITAL', 'UV_FLA', 'LARGE_FORMAT']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_deliverables', to='machines.machine')),
                ('cover_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_deliverables', to='papers.papertype')),
                ('finishings', models.ManyToManyField(blank=True, related_name='deliverables', through='orders.DeliverableFinishing', to='pricing.finishingservice')),
                ('inner_machine', models.ForeignKey(blank=True, limit_choices_to={'machine_type__in': ['DIGITAL', 'UV_FLA', 'LARGE_FORMAT']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inner_deliverables', to='machines.machine')),
                ('inner_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inner_deliverables', to='papers.papertype')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.finalpapersize')),
            ],
            options={
                'verbose_name': 'job deliverable',
                'verbose_name_plural': 'job deliverables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverablefinishing',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.jobdeliverable'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_ref', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Job Reference')),
                ('name', models.CharField(help_text="Short description e.g. 'Business cards for ACME'", max_length=120)),
                ('status', models.CharField(choices=[('pending_quote', 'Pending Quote'), ('quote_sent', 'Quote Sent'), ('quote_accepted', 'Quote Accepted'), ('paid', 'Paid'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_quote', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='The client/user who placed the order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(help_text='The print company assigned or requested for this order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.printcompany')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobdeliverable',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='deliverablefinishing',
            constraint=models.UniqueConstraint(fields=('deliverable', 'service', 'applies_to'), name='unique_finishing_per_scope'),
        ),
    ]
