# Generated by Django 5.2.4 on 2025-10-21 21:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to', models.CharField(choices=[('cover', 'Cover only'), ('inner', 'Inner pages only'), ('whole', 'Entire product')], default='whole', max_length=8)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.machine')),
            ],
            options={
                'verbose_name': 'Deliverable Finishing',
                'verbose_name_plural': 'Deliverable Finishings',
            },
        ),
        migrations.CreateModel(
            name='DeliverableMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to', models.CharField(choices=[('cover', 'Cover only'), ('inner', 'Inner pages only'), ('whole', 'Entire product')], default='whole', max_length=8)),
                ('usage_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('setup_cost_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.machine')),
            ],
            options={
                'verbose_name': 'Deliverable Machine',
                'verbose_name_plural': 'Deliverable Machines',
            },
        ),
        migrations.CreateModel(
            name='DeliverableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to', models.CharField(choices=[('cover', 'Cover only'), ('inner', 'Inner pages only'), ('whole', 'Entire product')], default='whole', max_length=8)),
                ('sides', models.CharField(choices=[('S1', 'Single-sided'), ('S2', 'Double-sided')], default='S1', max_length=2)),
                ('sheet_count', models.PositiveIntegerField(default=0)),
                ('unit_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.papertype')),
            ],
            options={
                'verbose_name': 'Deliverable Material',
                'verbose_name_plural': 'Deliverable Materials',
            },
        ),
        migrations.CreateModel(
            name='JobDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(default=1)),
                ('binding', models.CharField(choices=[('NONE', 'None'), ('SADDLE', 'Saddle Stitch'), ('PERFECT', 'Perfect Bind')], default='NONE', max_length=12)),
                ('sides', models.CharField(choices=[('S1', 'Single-sided'), ('S2', 'Double-sided')], default='S2', max_length=2)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('finishings', models.ManyToManyField(blank=True, related_name='finishing_jobs', through='orders.DeliverableFinishing', to='machines.machine')),
                ('machines', models.ManyToManyField(related_name='deliverables_machines', through='orders.DeliverableMachine', to='machines.machine')),
                ('materials', models.ManyToManyField(related_name='deliverables', through='orders.DeliverableMaterial', to='papers.papertype')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.finalpapersize')),
            ],
            options={
                'verbose_name': 'Job Deliverable',
                'verbose_name_plural': 'Job Deliverables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverablematerial',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.jobdeliverable'),
        ),
        migrations.AddField(
            model_name='deliverablemachine',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.jobdeliverable'),
        ),
        migrations.AddField(
            model_name='deliverablefinishing',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.jobdeliverable'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_ref', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Job Reference')),
                ('name', models.CharField(help_text="Short description e.g. 'Business cards for ACME'", max_length=120)),
                ('status', models.CharField(choices=[('pending_quote', 'Pending Quote'), ('quote_sent', 'Quote Sent'), ('quote_accepted', 'Quote Accepted'), ('paid', 'Paid'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_quote', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instant_quote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(help_text='The client/user who placed the order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(help_text='The print company assigned or requested for this order.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.printcompany')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobdeliverable',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverablematerial',
            unique_together={('deliverable', 'material', 'applies_to')},
        ),
        migrations.AlterUniqueTogether(
            name='deliverablemachine',
            unique_together={('deliverable', 'machine', 'applies_to')},
        ),
        migrations.AlterUniqueTogether(
            name='deliverablefinishing',
            unique_together={('deliverable', 'machine', 'applies_to')},
        ),
    ]
