# Generated by Django 5.2.4 on 2025-10-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_notes',
        ),
        migrations.AddField(
            model_name='jobdeliverable',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The calculated total price for this deliverable.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='jobdeliverable',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='papers.finalpapersize'),
        ),
    ]
