# Generated by Django 5.2.4 on 2025-09-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_custom_notes_order_instant_quote_price'),
        ('products', '0002_producttemplate_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdeliverable',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='The product template this deliverable is based on, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='products.producttemplate'),
        ),
    ]
