# Generated by Django 5.2.5 on 2025-09-14 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('deliverable', models.CharField(max_length=50, verbose_name='deliverable')),
                ('page_step', models.PositiveIntegerField(default=2, help_text='Enforce even pages (e.g., 4 pages for booklets).')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=100, verbose_name='minimum order quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.printcompany', verbose_name='company')),
                ('cover_range_gsm', models.ManyToManyField(related_name='cover_templates', to='papers.papertype')),
                ('insert_range_gsm', models.ManyToManyField(related_name='insert_templates', to='papers.papertype')),
                ('mandatory_finishings', models.ManyToManyField(blank=True, related_name='mandatory_templates', to='machines.machine')),
                ('optional_finishings', models.ManyToManyField(blank=True, related_name='optional_templates', to='machines.machine')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.finalpapersize', verbose_name='size')),
            ],
            options={
                'verbose_name': 'digital template',
                'verbose_name_plural': 'digital templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the image.', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.producttemplate', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['order'],
            },
        ),
    ]
