# Generated by Django 5.2.5 on 2025-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
